-- ============================================================================
-- CHO Appointment System — Oracle Database Schema
-- Run this as your application schema owner (e.g. in SQL*Plus / SQL Developer
-- / Oracle APEX SQL Workshop) after creating the user.
--
--   CREATE USER cho_app IDENTIFIED BY "<strong-password>";
--   GRANT CONNECT, RESOURCE TO cho_app;
--   ALTER USER cho_app QUOTA UNLIMITED ON USERS;
--
-- Boolean flags are stored as NUMBER(1) (0/1) because Oracle has no native
-- BOOLEAN column type. The application converts automatically.
-- ============================================================================

CREATE TABLE APPOINTMENTS (
  ID                              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                                  CONSTRAINT PK_APPOINTMENTS PRIMARY KEY,
  CREATED_AT                      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT                      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

  -- Patient Information
  FULL_NAME                       VARCHAR2(255) NOT NULL,
  AGE                             NUMBER NOT NULL,
  BIRTHDATE                       DATE,
  GENDER                          VARCHAR2(20),
  CIVIL_STATUS                    VARCHAR2(30),
  RESIDENTIAL_ADDRESS             VARCHAR2(500),
  CONTACT_NUMBER                  VARCHAR2(50),
  SPOUSE_NAME                     VARCHAR2(255),
  MOTHERS_MAIDEN_NAME             VARCHAR2(255),
  EMPLOYMENT_STATUS               VARCHAR2(50),
  PRIMARY_CARE_BENEFIT_MEMBER     NUMBER(1) DEFAULT 0 NOT NULL
                                  CONSTRAINT CK_APT_PCB CHECK (PRIMARY_CARE_BENEFIT_MEMBER IN (0, 1)),

  -- Health Facility Information
  CONSULTING_FACILITY             VARCHAR2(255) NOT NULL,
  YAKAP_REGISTERED                NUMBER(1) DEFAULT 0 NOT NULL
                                  CONSTRAINT CK_APT_YAKAP CHECK (YAKAP_REGISTERED IN (0, 1)),
  YAKAP_FACILITY                  VARCHAR2(255),

  -- Service Selection
  SERVICE_TYPE                    VARCHAR2(100) NOT NULL,
  APPOINTMENT_DATE                DATE NOT NULL,
  APPOINTMENT_TIME                VARCHAR2(20),

  -- Program & Coverage
  PHILHEALTH_MEMBER               NUMBER(1) DEFAULT 0 NOT NULL
                                  CONSTRAINT CK_APT_PHIC CHECK (PHILHEALTH_MEMBER IN (0, 1)),
  PHILHEALTH_NUMBER               VARCHAR2(50),
  PHILHEALTH_STATUS               VARCHAR2(20),
  FACILITY_HOUSEHOLD_NUMBER       VARCHAR2(50),
  PWD                             NUMBER(1) DEFAULT 0 NOT NULL
                                  CONSTRAINT CK_APT_PWD CHECK (PWD IN (0, 1)),

  -- Consent
  DATA_PRIVACY_CONSENT            NUMBER(1) DEFAULT 0 NOT NULL
                                  CONSTRAINT CK_APT_CONSENT CHECK (DATA_PRIVACY_CONSENT IN (0, 1)),

  -- Additional Notes
  NOTES                           CLOB
);

-- Indexes for the admin dashboard queries
CREATE INDEX IDX_APPOINTMENTS_DATE ON APPOINTMENTS (APPOINTMENT_DATE);
CREATE INDEX IDX_APPOINTMENTS_FACILITY ON APPOINTMENTS (CONSULTING_FACILITY);
CREATE INDEX IDX_APPOINTMENTS_SERVICE ON APPOINTMENTS (SERVICE_TYPE);
CREATE INDEX IDX_APPOINTMENTS_CREATED ON APPOINTMENTS (CREATED_AT DESC);

-- Optional sample row (remove in production):
-- INSERT INTO APPOINTMENTS (FULL_NAME, AGE, CONSULTING_FACILITY, SERVICE_TYPE, APPOINTMENT_DATE)
-- VALUES ('Dela Cruz, Juan A.', 34, 'Bacolod City Health Office', 'Medical Consultation', DATE '2026-09-07');
-- COMMIT;
